name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy Stage
      if: github.repository == 'teva-shalem/books-staging'
      uses: crazy-max/ghaction-github-pages@v2.1.0
      with:
        build_dir: dist
        fqdn: books-staging.teva-shalem.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy World
      if: github.repository == 'teva-shalem/books-world'
      uses: crazy-max/ghaction-github-pages@v2.1.0
      with:
        build_dir: dist
        fqdn: books.teva-shalem.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
